$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/end.png
    blur_passes = 2
    blur_size = 1
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(169 , 169 , 169 , 1.0) # no fill

    outer_color = rgba(96ffffFF) rgba(007fffFF) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(96ffff)
    fade_on_empty = false
    rounding = 15

    font_family = JetBrainsMono Nerd Font
    placeholder_text = Back to work endmin? 
    fail_text = $PAMFAIL$FPRINTFAIL

    # uncomment if you wish to display a message during authentication
    # check_text = Authenticating...

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}
# TIME
label {
    monitor =
    text = cmd[update:1000] date +"%I:%M %p" # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable>
    color = rgba(8afcffFF) 
    font_size = 50
    font_family = JetBrainsMono Nerd Font

    position = 0, -100
    halign = center
    valign = top
}

# DATE
label {
            monitor =
            text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
            color = rgba(8afcffFF) 
            font_size = 20
            font_family = JetBrainsMono Nerd Font

            position = 0, 100
            halign = center
            valign = bottom
        }

        label {
            monitor =
            text = $LAYOUT[en,ru]
            font_size = 24
            onclick = hyprctl switchxkblayout all next

            position = 250, -20
            halign = center
            valign = center
        }
label {
    monitor = 
    text = Tired already endmin?
    color = rgba(8afcffFF) 
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0,130
    halign = center
    valign = center
}
image {
    monitor = 
    path = ~/Pictures/perli.png
    size = 100
    border_size = 0
    position = -150, 57
    halign = center
    valign = center
}
image {
    monitor = 
    path = ~/Pictures/scared.png
    size = 600
    border_size = 0
    position = 166, 30
    halign = center
    valign = center
}
